server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-order

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: hystrixOrder80
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
